package com.agrioptima.solver;

import com.agrioptima.model.Crop;
import com.agrioptima.model.FarmState;
import com.agrioptima.model.FarmState.PlotState;

import java.util.List;
import java.util.Map;

/**
 * PlanReconstructor.java
 * 
 * Purpose: Reconstructs the optimal seasonal planting schedule from the 
 * backpointers stored by DPSolver during the dynamic programming phase.
 * 
 * How it works:
 * 1. Starts at the initial FarmState.
 * 2. Looks up the best assignment for that state in the backpointer map.
 * 3. Records the crop names for the current season.
 * 4. Transitions to the next state using StateManager logic.
 * 5. Repeats until all seasons are covered.
 */
public class PlanReconstructor {

    private final Map<FarmState, int[]> backpointer;
    private final int totalSeasons;
    private final int numPlots;
    private final List<Crop> cropList;
    private final StateManager stateManager;

    /**
     * Constructor
     * @param backpointer The map generated by DPSolver (State -> Best Assignment)
     * @param initialState The starting state used in DPSolver.solve()
     * @param cropList The list of available crops (to convert IDs to Names)
     * @param stateManager Used to simulate state transitions during reconstruction
     */
    public PlanReconstructor(
            Map<FarmState, int[]> backpointer, 
            FarmState initialState, 
            List<Crop> cropList, 
            StateManager stateManager) {
        
        if (backpointer == null) throw new IllegalArgumentException("Backpointer map cannot be null");
        if (initialState == null) throw new IllegalArgumentException("Initial state cannot be null");
        if (cropList == null || cropList.isEmpty()) throw new IllegalArgumentException("Crop list cannot be empty");
        if (stateManager == null) throw new IllegalArgumentException("StateManager cannot be null");

        this.backpointer = backpointer;
        this.totalSeasons = stateManager.getTotalSeasons();
        this.numPlots = stateManager.getNumPlots();
        this.cropList = cropList;
        this.stateManager = stateManager;
    }

    /**
     * Reconstructs the full seasonal plan.
     * @return A 2D array where result[seasonIndex][plotIndex] = Crop Name
     */
    public String[][] reconstructSchedule() {
        // We need to recreate the path. Since we don't store the whole path in memory,
        // we simulate the transitions starting from the initial state.
        // Note: We need the initial state passed in constructor or retrieved from solver.
        // For this implementation, we assume the user passes the initial state used in solve().
        // However, since we don't have initialState in fields yet, let's adjust constructor or method.
        // Correction: Let's require initialState in the reconstruct method or store it.
        // Better approach: The DPSolver usually stores initialState. Let's assume we pass it in method.
        
        // Actually, looking at DPSolver, it has getInitialState(). 
        // Let's make this method accept the initial state to be safe.
        throw new UnsupportedOperationException("Use reconstructSchedule(FarmState initialState) instead");
    }

    /**
     * Reconstructs the full seasonal plan starting from the given state.
     * @param initialState The state at Season 0 used when calling DPSolver.solve()
     * @return A 2D array where result[seasonIndex][plotIndex] = Crop Name
     */
    public String[][] reconstructSchedule(FarmState initialState) {
        String[][] schedule = new String[totalSeasons][numPlots];
        
        FarmState currentState = initialState;

        for (int season = 0; season < totalSeasons; season++) {
            // Retrieve the best assignment for the current state
            int[] assignment = backpointer.get(currentState);

            if (assignment == null) {
                // Edge Case: No valid assignment found for this state (dead end)
                // Fill remaining seasons with "Fallow" or "None"
                for (int s = season; s < totalSeasons; s++) {
                    for (int p = 0; p < numPlots; p++) {
                        schedule[s][p] = "Fallow (No Valid Plan)";
                    }
                }
                break; 
            }

            // Convert Crop IDs to Crop Names for this season
            for (int plot = 0; plot < numPlots; plot++) {
                int cropId = assignment[plot];
                if (cropId >= 0 && cropId < cropList.size()) {
                    schedule[season][plot] = cropList.get(cropId).getName();
                } else {
                    schedule[season][plot] = "Unknown Crop";
                }
            }

            // Transition to the next state to continue the loop
            // We must replicate the logic in StateManager.transition exactly
            currentState = transitionState(currentState, assignment);
        }

        return schedule;
    }

    /**
     * Helper to simulate state transition during reconstruction.
     * Mirrors StateManager.transition logic to ensure we follow the exact same path.
     */
    private FarmState transitionState(FarmState current, int[] assignment) {
        PlotState[] newPlotStates = new PlotState[numPlots];
        int totalWaterUsed = 0;

        for (int i = 0; i < numPlots; i++) {
            Crop crop = cropList.get(assignment[i]);
            
            // Calculate new soil level (clamped 0-2)
            int currentSoil = current.getPlotStates()[i].soilNitrogenLevel;
            int newSoil = Math.max(0, Math.min(2, currentSoil + crop.getNitrogenImpact()));

            newPlotStates[i] = new PlotState(crop.getId(), newSoil);
            totalWaterUsed += crop.getWaterPerAcre();
        }

        return new FarmState(
            current.getSeason() + 1,
            newPlotStates,
            current.getRemainingWater() - totalWaterUsed
        );
    }

    /**
     * Calculates summary metrics for the reconstructed plan.
     * Useful for displaying "Total Profit", "Water Used", etc.
     */
    public PlanMetrics calculateMetrics(FarmState initialState, String[][] schedule) {
        int totalProfit = 0;
        int totalWaterUsed = 0;
        int initialSoilSum = 0;
        int finalSoilSum = 0;

        // Calculate initial soil sum
        for (PlotState ps : initialState.getPlotStates()) {
            initialSoilSum += ps.soilNitrogenLevel;
        }

        FarmState currentState = initialState;

        for (int season = 0; season < totalSeasons; season++) {
            int[] assignment = backpointer.get(currentState);
            if (assignment == null) break;

            double seasonalMultiplier = (season % 2 == 1) ? 1.1 : 1.0; // Match DPSolver logic

            for (int plot = 0; plot < numPlots; plot++) {
                Crop crop = cropList.get(assignment[plot]);
                
                // Profit
                totalProfit += (int) (crop.getProfitPerAcre() * seasonalMultiplier);
                
                // Water
                totalWaterUsed += crop.getWaterPerAcre();
            }

            // Move state forward to capture final soil status
            currentState = transitionState(currentState, assignment);
        }

        // Calculate final soil sum
        if (currentState != null) {
            for (PlotState ps : currentState.getPlotStates()) {
                finalSoilSum += ps.soilNitrogenLevel;
            }
        }

        return new PlanMetrics(totalProfit, totalWaterUsed, initialSoilSum, finalSoilSum);
    }

    /**
     * Inner class to hold calculated metrics.
     * You can move this to a separate file PlanMetrics.java if preferred.
     */
    public static class PlanMetrics {
        public final int totalProfit;
        public final int totalWaterUsed;
        public final int soilHealthChange; // Difference in sum of soil levels

        public PlanMetrics(int profit, int water, int initialSoil, int finalSoil) {
            this.totalProfit = profit;
            this.totalWaterUsed = water;
            this.soilHealthChange = finalSoil - initialSoil;
        }

        // Getters for Jackson JSON serialization
        public int getTotalProfit() { return totalProfit; }
        public int getTotalWaterUsed() { return totalWaterUsed; }
        public int getSoilHealthChange() { return soilHealthChange; }

        @Override
        public String toString() {
            return String.format("Profit: ₹%,d | Water Used: %dL | Soil Change: %+d",
                totalProfit, totalWaterUsed, soilHealthChange);
        }
    }
}